sudo: false
language: php

php:
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    - mkdir -p build/logs
    - mkdir -p build/cov

before_install:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install

script:
    - ./vendor/bin/phpunit -c phpunit.xml.dist

jobs:
    allow_failures:
        - php: nightly

    include:
        - stage: Metrics and quality
          env: COVERAGE
          before_script:
              - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
              - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
              - wget https://phar.phpunit.de/phpcov.phar
              - chmod +x phpcov.phar
              - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
              - chmod +x php-coveralls.phar
          script:
              - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-php build/cov/coverage.cov
          after_script:
              - phpcov.phar merge --clover build/logs/clover.xml build/cov
              - php-coveralls.phar --no-interaction

        - stage: Metrics and quality
          env: STATIC_ANALYSIS
          script:
              - ./vendor/bin/phpstan analyse

        - stage: Metrics and quality
          env: CODING_STANDARDS
          before_script:
              - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
              - chmod a+x php-cs-fixer
          script:
              - ./php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no

        - stage: Security Check
          env: SECURITY_CHECK
          before_script:
              - wget -c https://get.sensiolabs.org/security-checker.phar
              - chmod +x security-checker.phar
          script:
              - ./security-checker.phar security:check
